baseURL: 'https://ondrejmarkus.com/'
languageCode: en-us
theme: PaperMod
title: Ondrej Markus

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

permalinks:
  blog: '/:slug/'
  pages: '/:slug/'
  archives: '/:slug/'

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "A designer based in Amsterdam, exploring what makes games remarkable."
  keywords: [ondrej markus, blog, game design, games]
  author: Ondrej Markus
  images: 
  DateFormat: "January 2, 2006"
  defaultTheme: light # dark, light

  ShowReadingTime: true
  hideFooter: true

  disableThemeToggle: false
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false


  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: /favicon/favicon.ico
    favicon16x16: /favicon/favicon16x16.png
    favicon32x32: /favicon/favicon32x32.png
    apple_touch_icon: /favicon/apple-touch-icon.png
    safari_pinned_tab: /favicon/apple-touch-icon.png

  label:
    text: "Ondrej Markus"

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: Hey there, I'm Ondrej.
    subtitle: "A designer exploring how games improve our lives."
    imageUrl: 
    imageWidth: auto
    imageHeight: auto
    imageTitle: my image
    buttons:
      - name: Articles
        url: blog

  # home-info mode
  homeInfoParams:
    Title: Hey there, I'm Ondrej.
    Content: |

      I'm a **designer**, **entrepreneur**, and **writer**.

      This is my [digital garage](/open-garage/) where you can [follow my work](/now/) and learning process.

      Living and biking everywhere in **Amsterdam**.

  socialIcons:
    - name: twitter
      url: https://twitter.com/ondrej_markus

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: blog
      name: Articles
      url: /blog/
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 3
    - identifier: 
      name: 
      url: https://craft.ondrejmarkus.com/
      weight: 
    - identifier: emails
      name: Newsletter
      url: https://www.getrevue.co/profile/ondrej_markus
      weight: 4

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai